## INFO 371 Problem Set 5

*Name*: Xiaobing Xu

*Teammate*: Quynh Doan (Thx for providing ideas on explanation)

*Section*: INFO 371 AA

*Date*: April 28th, 2022

In [1]:
import pandas as pd
import numpy as np
import textwrap

### 1.1

In [2]:
emails = pd.read_csv("../Data/all-data/lingspam-emails.csv.bz2",sep='\t')
emails.head()

spam          files                                            message
0  False    3-1msg1.txt  Subject: re : 2 . 882 s - > np np  > date : su...
1  False    3-1msg2.txt  Subject: s - > np + np  the discussion of s - ...
2  False    3-1msg3.txt  Subject: 2 . 882 s - > np np  . . . for me it ...
3  False  3-375msg1.txt  Subject: gent conference  " for the listserv "...
4  False  3-378msg1.txt  Subject: query : causatives in korean  could a...

### 1.2

In [3]:
emails = emails.dropna(subset=['spam', 'message'])
emails.head()

spam          files                                            message
0  False    3-1msg1.txt  Subject: re : 2 . 882 s - > np np  > date : su...
1  False    3-1msg2.txt  Subject: s - > np + np  the discussion of s - ...
2  False    3-1msg3.txt  Subject: 2 . 882 s - > np np  . . . for me it ...
3  False  3-375msg1.txt  Subject: gent conference  " for the listserv "...
4  False  3-378msg1.txt  Subject: query : causatives in korean  could a...

### 2.1

In [4]:
list_of_words = ['viagra', 'deadline', 'million', 'and', 'drink', 'dear', 'update', 'billion', 'food', 'pizza']

### 2.2

In [10]:
for w in list_of_words:
    emails[w] = emails.message.str.lower().str.contains(w)

In [16]:
X = emails.iloc[:, 3:]
Y = emails.spam
X

viagra  deadline  million    and  drink   dear  update  billion   food  \
0      False     False    False   True  False  False   False    False  False   
1      False     False    False  False  False  False   False    False  False   
2      False     False    False  False  False  False   False    False  False   
3      False     False    False   True   True  False   False    False   True   
4      False     False    False   True  False  False   False    False  False   
...      ...       ...      ...    ...    ...    ...     ...      ...    ...   
2888   False     False    False   True  False  False   False    False  False   
2889   False     False     True   True  False  False   False    False  False   
2890   False     False    False   True  False  False   False    False  False   
2891   False     False     True   True  False  False   False    False  False   
2892   False     False     True   True  False  False    True    False  False   

      pizza  
0     False  
1     False  
2     False  
3     False  
4     False  
...     ...  
2888  False  
2889  False  
2890  False  
2891  False  
2892  False  

[2893 rows x 10 columns]

### 2.3

In [12]:
from sklearn.model_selection import train_test_split

Xt, Xv, Yt, Yv = train_test_split(X, Y)

In [13]:
Xv

viagra  deadline  million    and  drink   dear  update  billion   food  \
2590   False     False    False   True  False  False   False    False  False   
1274   False     False    False   True  False  False   False    False  False   
2535   False     False    False   True  False  False   False    False  False   
281    False     False    False   True  False  False   False    False  False   
120    False     False    False  False  False  False   False    False  False   
...      ...       ...      ...    ...    ...    ...     ...      ...    ...   
2198   False      True    False   True  False  False   False    False  False   
2401   False     False    False  False  False  False   False    False  False   
1557   False      True    False   True  False  False   False    False  False   
2298   False     False    False   True  False  False   False    False  False   
1230   False     False    False   True  False  False   False    False  False   

      pizza  
2590  False  
1274  False  
2535  False  
281   False  
120   False  
...     ...  
2198  False  
2401  False  
1557  False  
2298  False  
1230  False  

[724 rows x 10 columns]

In [14]:
Yv

2590     True
1274    False
2535    False
281      True
120     False
        ...  
2198    False
2401    False
1557    False
2298     True
1230    False
Name: spam, Length: 724, dtype: bool

### 3.1

- `P_S`: Pr(category = S)
- `P_NS`: Pr(category = NS)
- `P_W`: Pr(word = 1)
- `P_NW`: Pr(word = 0)
- `P_W_S`: Pr(word = 1 | category = S)
- `P_NW_S`: Pr(word = 0 | category = S)
- `P_W_NS`: Pr(word = 1 | category = NS)
- `P_NW_NS`: Pr(word = 0 | category = NS)

### 3.2

In [43]:
P_S = np.mean(Yt)
P_NS = 1 - P_S
print("Probability of spam: ", P_S)
print("Probability of non-spam: ", P_NS)

Probability of spam:  0.16044260027662519
Probability of non-spam:  0.8395573997233748


### 3.3

In [45]:
for w in list_of_words:
    print(f'{w}: P_W = {round(np.mean(Xt[w]), 3)}')
    print(f'{w}: P_NW = {round(np.mean(Xt[w] == False), 3)}')

viagra: P_W = 0.0
viagra: P_NW = 1.0
deadline: P_W = 0.146
deadline: P_NW = 0.854
million: P_W = 0.047
million: P_NW = 0.953
and: P_W = 0.941
and: P_NW = 0.059
drink: P_W = 0.007
drink: P_NW = 0.993
dear: P_W = 0.066
dear: P_NW = 0.934
update: P_W = 0.046
update: P_NW = 0.954
billion: P_W = 0.012
billion: P_NW = 0.988
food: P_W = 0.012
food: P_NW = 0.988
pizza: P_W = 0.001
pizza: P_NW = 0.999


### 3.4

In [46]:
for w in list_of_words:
    print(f'{w}: P_W_S = {round(np.mean(Xt[w][Yt]), 3)}')
    print(f'{w}: P_W_NS = {round(np.mean(Xt[w][Yt == False]), 3)}')

viagra: P_W_S = 0.003
viagra: P_W_NS = 0.0
deadline: P_W_S = 0.0
deadline: P_W_NS = 0.174
million: P_W_S = 0.241
million: P_W_NS = 0.01
and: P_W_S = 0.925
and: P_W_NS = 0.945
drink: P_W_S = 0.009
drink: P_W_NS = 0.007
dear: P_W_S = 0.103
dear: P_W_NS = 0.059
update: P_W_S = 0.089
update: P_W_NS = 0.038
billion: P_W_S = 0.066
billion: P_W_NS = 0.001
food: P_W_S = 0.026
food: P_W_NS = 0.009
pizza: P_W_S = 0.003
pizza: P_W_NS = 0.001


### 3.5

In [47]:
for w in list_of_words:
    print(f'{w}: P_S_W = {np.mean(Xt[w][Yt]) * P_S / (np.mean(Xt[w][Yt]) * P_S + np.mean(Xt[w][Yt == False] * P_NS))}')
    print(f'{w}: P_S_NW = {np.mean((Xt[w] == False)[Yt]) * P_S / (np.mean((Xt[w] == False)[Yt]) * P_S + np.mean((Xt[w] == False)[Yt == False]) * P_NS)}')

viagra: P_S_W = 1.0
viagra: P_S_NW = 0.16005535055350556
deadline: P_S_W = 0.0
deadline: P_S_NW = 0.1879049676025918
million: P_S_W = 0.8235294117647058
million: P_S_NW = 0.1277213352685051
and: P_S_W = 0.15768854064642335
and: P_S_NW = 0.20472440944881895
drink: P_S_W = 0.2
drink: P_S_NW = 0.16016713091922008
dear: P_S_W = 0.25174825174825166
dear: P_S_NW = 0.15399802566633763
update: P_S_W = 0.30999999999999994
update: P_S_NW = 0.15321411309811503
billion: P_S_W = 0.92
billion: P_S_NW = 0.15158582089552242
food: P_S_W = 0.3461538461538461
food: P_S_NW = 0.15818945403639756
pizza: P_S_W = 0.5000000000000001
pizza: P_S_NW = 0.16012921089063223


### 3.6

Only `P_W` `P_NW` `P_S` `P_NS` have to sum to unity. Others are not. This is because no situations when both probabilities happen at the same time. The P_W_S cannot be added up to 1 with P_W_NS, since thre are no extra cases outside of these probabilities, happening alongside them.

### 3.7 & 3.8

In [68]:
from sklearn.metrics import confusion_matrix

for w in list_of_words:
    P_S_W = np.mean(Xt[w][Yt]) * P_S / (np.mean(Xt[w][Yt]) * P_S + np.mean(Xt[w][Yt == False] * P_NS))
    P_S_NW = np.mean((Xt[w] == False)[Yt]) * P_S / (np.mean((Xt[w] == False)[Yt]) * P_S + np.mean((Xt[w] == False)[Yt == False]) * P_NS)
    
    P = np.where(Xv[w], P_S_W, P_S_NW)
    y_hat = P > 0.5
    
    tn, fp, fn, tp = confusion_matrix(Yv, y_hat).ravel()
    precision = tp / (tp + fp)
    recall = tp / (tp + fn)
    
    print("Word: ", w)
    print(P_S_W, P_S_NW)
    print("Confusion Matrix:\n", confusion_matrix(Yv, y_hat))
    print("Accuracy: ", np.mean(y_hat == Yv))
    print("Precision: ", precision)
    print("Recall: ", recall, "\n")

Word:  viagra
1.0 0.16005535055350556
Confusion Matrix:
 [[591   0]
 [133   0]]
Accuracy:  0.8162983425414365
Precision:  nan
Recall:  0.0 

Word:  deadline
0.0 0.1879049676025918
Confusion Matrix:
 [[591   0]
 [133   0]]
Accuracy:  0.8162983425414365
Precision:  nan
Recall:  0.0 

Word:  million
0.8235294117647058 0.1277213352685051
Confusion Matrix:
 [[585   6]
 [101  32]]
Accuracy:  0.8522099447513812
Precision:  0.8421052631578947
Recall:  0.24060150375939848 

Word:  and
0.15768854064642335 0.20472440944881895
Confusion Matrix:
 [[591   0]
 [133   0]]
Accuracy:  0.8162983425414365
Precision:  nan
Recall:  0.0 

Word:  drink
0.2 0.16016713091922008
Confusion Matrix:
 [[591   0]
 [133   0]]
Accuracy:  0.8162983425414365
Precision:  nan
Recall:  0.0 

Word:  dear
0.25174825174825166 0.15399802566633763
Confusion Matrix:
 [[591   0]
 [133   0]]
Accuracy:  0.8162983425414365
Precision:  nan
Recall:  0.0 

Word:  update
0.30999999999999994 0.15321411309811503
Confusion Matrix:
 [[591   

<ipython-input-68-bdcc610397ad>:11: RuntimeWarning: invalid value encountered in long_scalars
  precision = tp / (tp + fp)
<ipython-input-68-bdcc610397ad>:11: RuntimeWarning: invalid value encountered in long_scalars
  precision = tp / (tp + fp)
<ipython-input-68-bdcc610397ad>:11: RuntimeWarning: invalid value encountered in long_scalars
  precision = tp / (tp + fp)
<ipython-input-68-bdcc610397ad>:11: RuntimeWarning: invalid value encountered in long_scalars
  precision = tp / (tp + fp)
<ipython-input-68-bdcc610397ad>:11: RuntimeWarning: invalid value encountered in long_scalars
  precision = tp / (tp + fp)
<ipython-input-68-bdcc610397ad>:11: RuntimeWarning: invalid value encountered in long_scalars
  precision = tp / (tp + fp)
<ipython-input-68-bdcc610397ad>:11: RuntimeWarning: invalid value encountered in long_scalars
  precision = tp / (tp + fp)
<ipython-input-68-bdcc610397ad>:11: RuntimeWarning: invalid value encountered in long_scalars
  precision = tp / (tp + fp)


### 3.9

Most of the emails are identified as negative(spam emails) and in some extreme cases that no emails are identified as spam. Thus, recall and making the precision are extremely low. The accuracy looks high when the emails in the files mostly are classfied as non-spam.

### 3.10

For the overall accuracy of the model is high, which is over 80%. However, except from millions and billions, in either cases, both of the probability are under 0.5 making all emails will be classified as negative(spam), which means that it is not a good model to identify positive examples

### 3.11

The reason of low recall while other indicators do not look back is because the model only correctly predicts few of actual spam emails as the spam. The accuracy is high due to the reason that the predictions of ratio of the spam and non spam emails are high compared with all predictions. 

### 3.12

- “million” improve accuracy since it appears with high frequency in spam emails. 
- "viagra" doesn't work because both the spam and non-spam emails don't have any occurrences of this word. 
- "deadline" also doesn't work because there's no occurrences of this word in spam emails, and very low occurrences in non-spam emails. 
- "and" doesn't work because there're very high occurrences of this word in both spam and non-spam emails. 

### 3.13 & 14

In [51]:
for w in list_of_words:
    P_S_W = (np.mean(Xt[w][Yt]) * P_S + 1) / (np.mean(Xt[w][Yt]) * P_S + 
                                        np.mean(Xt[w][Yt == False] * P_NS) + 2)
    P_S_NW = (np.mean((Xt[w] == False)[Yt]) + 1) * P_S / (np.mean((Xt[w] == False)[Yt]) * P_S + 
                                                    np.mean((Xt[w] == False)[Yt == False]) * P_NS + 2)
    
    
    P = np.where(Xv[w], P_S_W, P_S_NW)
    y_hat = P > 0.5
    
    tn, fp, fn, tp = confusion_matrix(Yv, y_hat).ravel()
    precision = tp / (tp + fp)
    recall = tp / (tp + fn)
    
    print("Word: ", w)
    print("Confusion Matrix:\n", confusion_matrix(Yv, y_hat))
    print("Accuracy: ", np.mean(y_hat == Yv))
    print("Precision: ", precision)
    print("Recall: ", recall, "\n")

Word:  viagra
Confusion Matrix:
 [[591   0]
 [133   0]]
Accuracy:  0.8162983425414365
Precision:  nan
Recall:  0.0 

Word:  deadline
Confusion Matrix:
 [[591   0]
 [133   0]]
Accuracy:  0.8162983425414365
Precision:  nan
Recall:  0.0 

Word:  million
Confusion Matrix:
 [[585   6]
 [101  32]]
Accuracy:  0.8522099447513812
Precision:  0.8421052631578947
Recall:  0.24060150375939848 

Word:  and
Confusion Matrix:
 [[591   0]
 [133   0]]
Accuracy:  0.8162983425414365
Precision:  nan
Recall:  0.0 

Word:  drink
Confusion Matrix:
 [[591   0]
 [133   0]]
Accuracy:  0.8162983425414365
Precision:  nan
Recall:  0.0 

Word:  dear
Confusion Matrix:
 [[591   0]
 [133   0]]
Accuracy:  0.8162983425414365
Precision:  nan
Recall:  0.0 

Word:  update
Confusion Matrix:
 [[591   0]
 [133   0]]
Accuracy:  0.8162983425414365
Precision:  nan
Recall:  0.0 

Word:  billion
Confusion Matrix:
 [[589   2]
 [130   3]]
Accuracy:  0.8176795580110497
Precision:  0.6
Recall:  0.022556390977443608 

Word:  food
Confus

<ipython-input-51-4e50f9b168c0>:12: RuntimeWarning: invalid value encountered in long_scalars
  precision = tp / (tp + fp)
<ipython-input-51-4e50f9b168c0>:12: RuntimeWarning: invalid value encountered in long_scalars
  precision = tp / (tp + fp)
<ipython-input-51-4e50f9b168c0>:12: RuntimeWarning: invalid value encountered in long_scalars
  precision = tp / (tp + fp)
<ipython-input-51-4e50f9b168c0>:12: RuntimeWarning: invalid value encountered in long_scalars
  precision = tp / (tp + fp)
<ipython-input-51-4e50f9b168c0>:12: RuntimeWarning: invalid value encountered in long_scalars
  precision = tp / (tp + fp)
<ipython-input-51-4e50f9b168c0>:12: RuntimeWarning: invalid value encountered in long_scalars
  precision = tp / (tp + fp)
<ipython-input-51-4e50f9b168c0>:12: RuntimeWarning: invalid value encountered in long_scalars
  precision = tp / (tp + fp)
<ipython-input-51-4e50f9b168c0>:12: RuntimeWarning: invalid value encountered in long_scalars
  precision = tp / (tp + fp)


According to the accuracy, precision, and recall above, the smoothing does not improve the overall performance. 