In [329]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [330]:
df = pd.read_csv("../Data/all-data/wdbc.csv.bz2")
df.head()

id diagnosis  radius.mean  texture.mean  perimeter.mean  area.mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness.mean  compactness.mean  concavity.mean  concpoints.mean  ...  \
0          0.11840           0.27760          0.3001          0.14710  ...   
1          0.08474           0.07864          0.0869          0.07017  ...   
2          0.10960           0.15990          0.1974          0.12790  ...   
3          0.14250           0.28390          0.2414          0.10520  ...   
4          0.10030           0.13280          0.1980          0.10430  ...   

   radius.worst  texture.worst  perimeter.worst  area.worst  smoothness.worst  \
0         25.38          17.33           184.60      2019.0            0.1622   
1         24.99          23.41           158.80      1956.0            0.1238   
2         23.57          25.53           152.50      1709.0            0.1444   
3         14.91          26.50            98.87       567.7            0.2098   
4         22.54          16.67           152.20      1575.0            0.1374   

   compactness.worst  concavity.worst  concpoints.worst  symmetry.worst  \
0             0.6656           0.7119            0.2654          0.4601   
1             0.1866           0.2416            0.1860          0.2750   
2             0.4245           0.4504            0.2430          0.3613   
3             0.8663           0.6869            0.2575          0.6638   
4             0.2050           0.4000            0.1625          0.2364   

   fracdim.worst  
0        0.11890  
1        0.08902  
2        0.08758  
3        0.17300  
4        0.07678  

[5 rows x 32 columns]

In [331]:
#2
df.drop("id",axis=1)
X = df.loc[:, df.columns != "diagnosis"].values
y = df.diagnosis.values

In [332]:
x = X
xbar = X.mean(axis = 0)
sdx = X.std(axis = 0)

In [333]:
Xn = (x - xbar)/sdx
Xn

array([[-0.23640517,  1.09706398, -2.07333501, ...,  2.29607613,
         2.75062224,  1.93701461],
       [-0.23640344,  1.82982061, -0.35363241, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 0.43174109,  1.57988811,  0.45618695, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [-0.23572747,  0.70228425,  2.0455738 , ...,  0.41406869,
        -1.10454895, -0.31840916],
       [-0.23572517,  1.83834103,  2.33645719, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-0.24240586, -1.80840125,  1.22179204, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [334]:
#4(a)
from sklearn.decomposition import PCA
m = PCA()
_ = m.fit(Xn)

In [335]:
#4(b)
explained_variance = m.explained_variance_ratio_
explained_variance

array([4.28647013e-01, 1.83767915e-01, 9.14643564e-02, 6.39147476e-02,
       5.31875905e-02, 3.98281519e-02, 3.15572013e-02, 2.16694506e-02,
       1.48642719e-02, 1.30042934e-02, 1.12630637e-02, 9.48033657e-03,
       8.42409435e-03, 7.78484562e-03, 5.06366610e-03, 3.03640406e-03,
       2.57451447e-03, 1.90471846e-03, 1.69649015e-03, 1.58457831e-03,
       1.00228336e-03, 9.65845343e-04, 8.84855607e-04, 7.82226523e-04,
       5.81914867e-04, 4.99346119e-04, 2.63603188e-04, 2.22519447e-04,
       5.12689531e-05, 2.41411630e-05, 4.29161956e-06])

In [336]:
#4(c)
cumulative_variance = np.cumsum(explained_variance)
cumulative_variance

array([0.42864701, 0.61241493, 0.70387928, 0.76779403, 0.82098162,
       0.86080977, 0.89236698, 0.91403643, 0.9289007 , 0.94190499,
       0.95316806, 0.96264839, 0.97107249, 0.97885733, 0.983921  ,
       0.9869574 , 0.98953192, 0.99143664, 0.99313313, 0.9947177 ,
       0.99571999, 0.99668583, 0.99757069, 0.99835291, 0.99893483,
       0.99943418, 0.99969778, 0.9999203 , 0.99997157, 0.99999571,
       1.        ])

In [337]:
principal_component = m.components_
pd.DataFrame(principal_component).head()

0         1         2         3         4         5         6   \
0  0.022912  0.218913  0.103844  0.227535  0.221046  0.142415  0.239067   
1 -0.034068 -0.233271 -0.060044 -0.214589 -0.230669  0.186422  0.152455   
2  0.096938 -0.011394  0.066892 -0.012125  0.026293 -0.103182 -0.074769   
3 -0.026598  0.042188 -0.602954  0.042753  0.054115  0.158098  0.031818   
4 -0.011328  0.038130 -0.049091  0.037716  0.010562 -0.365750  0.011787   

         7         8         9   ...        21        22        23        24  \
0  0.258280  0.260738  0.137978  ...  0.228009  0.104515  0.236637  0.224932   
1  0.060542 -0.034167  0.190685  ... -0.219296 -0.045501 -0.199296 -0.218985   
2  0.001759 -0.027580 -0.040962  ... -0.049406 -0.039829 -0.050432 -0.013189   
3  0.019497  0.065785  0.067503  ...  0.015660 -0.633120  0.014069  0.025971   
4  0.086513 -0.043667 -0.305379  ... -0.004280 -0.092552  0.007599 -0.027414   

         25        26        27        28        29        30  
0  0.127824  0.209885  0.228602  0.250746  0.122680  0.131560  
1  0.172563  0.144254  0.098527 -0.007534  0.142619  0.275702  
2 -0.255329 -0.234514 -0.172025 -0.170481 -0.270516 -0.229474  
3  0.014523 -0.092562 -0.074807  0.005306 -0.037129 -0.078971  
4 -0.325860  0.121503  0.188281  0.043124 -0.244246  0.093699  

[5 rows x 31 columns]

### 2 PC Regression

In [338]:
#1
Xr = m.transform(X)
Xr

array([[ 2.00925346e+04, -2.94670704e+04,  8.16743495e+04, ...,
         7.94891310e+01,  1.07826195e+03, -4.67781867e+01],
       [ 2.01354694e+04, -2.95214437e+04,  8.16875643e+04, ...,
        -2.05266266e+00,  9.23933108e+02, -2.62629298e+01],
       [ 1.93226732e+06, -2.87274120e+06,  8.17201812e+06, ...,
        -1.60333989e+03,  5.80516761e+04, -5.96600124e+03],
       ...,
       [ 2.17611357e+04, -3.20911801e+04,  8.98685397e+04, ...,
        -5.58692633e+01,  8.04513226e+02, -2.70424371e+01],
       [ 2.20471614e+04, -3.23742270e+04,  8.99027304e+04, ...,
        -3.70698785e+01,  9.49690239e+02, -2.60183885e+01],
       [ 2.26467976e+03, -3.29217548e+03,  8.99396878e+03, ...,
        -2.06476060e+01,  1.20544388e+02,  1.27641658e+01]])

In [339]:
#2 (a)
Xa = Xr[:,[0]]
m = LogisticRegression(max_iter = 140).fit(Xa,y)
cv = cross_val_score(m, Xa, y, cv=10)
cv.mean()

0.5782894736842106

In [340]:
#2 (b)
Xb = Xr[:,0:2]
m = LogisticRegression(max_iter = 140).fit(Xb,y)
cv = cross_val_score(m, Xb, y, cv=10)
cv.mean()

0.5782894736842106

In [346]:
#2 (c)
Xc = Xr[:,0:3]
m = LogisticRegression(max_iter = 140).fit(Xc,y)
cv = cross_val_score(m, Xc, y,scoring = 'accuracy', cv=10)
cv.mean()

0.8927318295739349

In [345]:
#3
X = df[["smoothness.mean","perimeter.mean","texture.mean"]].values
y = df.diagnosis.values
Xn = np.empty_like(X)
for i in range(X.shape[1]):
    Xn[:,i] = (X[:,i] - X[:,i].mean())/X[:,i].std()
m = PCA()
_ = m.fit(Xn)

Xr = m.transform(X)
X1 = Xr[:,[0]]
m1 = LogisticRegression(max_iter = 140).fit(X1,y)
cross_val_score(m1, X1, y,scoring = 'accuracy', cv=10).mean()

0.8963345864661655

In [343]:
X = df[["compactness.mean","concavity.mean","radius.worst"]].values
y = df.diagnosis.values
for i in range(X.shape[1]):
    Xn[:,i] = (X[:,i] - X[:,i].mean())/X[:,i].std()
m = PCA()
_ = m.fit(Xn)

Xr = m.transform(X)
X1 = Xr[:,[0]]
m1 = LogisticRegression(max_iter = 140).fit(X1,y)
cross_val_score(m1, X1, y, cv=10).mean()

0.9139411027568922

In [344]:
X = df[["concpoints.worst","fracdim.worst","smoothness.mean"]].values
y = df.diagnosis.values
for i in range(X.shape[1]):
    Xn[:,i] = (X[:,i] - X[:,i].mean())/X[:,i].std()
m = PCA()
_ = m.fit(Xn)

Xr = m.transform(X)
X1 = Xr[:,[0]]
m1 = LogisticRegression(max_iter = 140).fit(X1,y)
cross_val_score(m1, X1, y, cv=10).mean()

0.7135338345864661

The best value I get is 91.4%